### ISSUE TITLE
Uninstalling plugin installed by new method in Ubuntu 16.04 crashes

### ISSUE THREAD

**Issue by jongough** [mauroc/squiddio_pi#111]
I installed testplugin_pi using the new method. It installed OK, but when clicking on the uninstall button OCPN gets a segmentation fault. These are the last entries in the opencpn.log
```
07:40:47 AEDT: Loading plugins from dir: /usr/local/lib/opencpn/opencpn
07:40:47 AEDT: PlugInManager searching for PlugIns in location /usr/local/lib/opencpn/opencpn
07:40:47 AEDT:    Directory /usr/local/lib/opencpn/opencpn does not exist.
07:40:47 AEDT: install: Reloading plugins, before: 5, after:  6
07:40:54 AEDT: PlugInManager: Deactivating PlugIn: /home/jon/.local/lib/opencpn/libtestplugin_pi.so
```
This is the gdb bt:
```
(gdb) bt
#0  0x00007ffff5d94402 in wxWindowBase::SendIdleEvents(wxIdleEvent&) ()
   from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#1  0x00007ffff5d94408 in wxWindowBase::SendIdleEvents(wxIdleEvent&) ()
   from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#2  0x00007ffff5c0adbf in wxFrame::SendIdleEvents(wxIdleEvent&) ()
   from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#3  0x00007ffff5c5159d in wxAppBase::ProcessIdle() ()
   from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#4  0x00007ffff5b5dace in wxApp::DoIdle() () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#5  0x00007ffff5b5dbb3 in ?? () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#6  0x00007fffef39704a in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007fffef3973f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007fffef397712 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007fffef9b0697 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#10 0x00007ffff5b7ded5 in wxGUIEventLoop::DoRun() ()
   from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#11 0x00007ffff5527353 in wxEventLoopBase::Run() () from /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#12 0x00007ffff5c00cdd in wxDialog::ShowModal() ()
   from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#13 0x00000000005b4628 in MyFrame::DoOptionsDialog() ()
#14 0x00000000005b5080 in ?? ()
#15 0x00000000005b7aac in MyFrame::OnToolLeftClick(wxCommandEvent&) ()
#16 0x00007ffff54e51fe in wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const () from /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#17 0x00007ffff566b6e7 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) () from /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#18 0x00007ffff566b7db in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) ()
   from /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#19 0x00007ffff566bb8b in wxEvtHandler::TryHereOnly(wxEvent&) ()
   from /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#20 0x00007ffff566b993 in wxEvtHandler::DoTryChain(wxEvent&) ()
   from /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#21 0x00007ffff566bc75 in wxEvtHandler::ProcessEvent(wxEvent&) ()
   from /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#22 0x00007ffff566c6fa in wxEvtHandler::ProcessPendingEvents() ()
   from /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#23 0x00007ffff54e7317 in wxAppConsoleBase::ProcessPendingEvents() ()
---Type <return> to continue, or q <return> to quit---
  x_baseu-3.0.so.0
#24 0x00007ffff5b5dac2 in wxApp::DoIdle() () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#25 0x00007ffff5b5dbb3 in ?? () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#26 0x00007fffef39704a in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007fffef3973f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007fffef397712 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007fffef9b0697 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#30 0x00007ffff5b7ded5 in wxGUIEventLoop::DoRun() ()
   from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#31 0x00007ffff5527353 in wxEventLoopBase::Run() () from /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#32 0x00007ffff54ec666 in wxAppConsoleBase::MainLoop() ()
   from /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#33 0x00007ffff5578f70 in wxEntry(int&, wchar_t**) ()
   from /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#34 0x00000000004e3198 in main ()
(gdb)
```
The opencpn install is from opencpn-xenial_5.0.0+744.c270732-1_amd64.deb downloaded from cloudsmith. testplugin_pi is from cloudsmith using this xml inserted into the ocpn-plugins.xml
```
<plugin version="1">
  <name> testplugin </name>
  <version> 1.0.41 </version>
  <release> 0 </release>
  <summary> Plugin to enable  </summary>

  <api-version> 1.16 </api-version>
  <open-source> yes </open-source>
  <author> Jon Gough </author>
  <source> https://github.com/jongough/testplugin_pi </source>

  <description>
    testplugin 
  </description>

  <target>ubuntu</target>
  <target-version>16.04</target-version>
  <tarball-url>
    https://dl.cloudsmith.io/public/jon-gough/testplugin_pi-beta/raw/names/testplugin-ubuntu-16.04-tarball/versions/1.0.41.0+325.91137b2/opencpn-plugin-testplugin-1.0.41.0-ov50-1.16_ubuntu-16.04.tar.gz
  </tarball-url>
  <info-url> https://opencpn.org/OpenCPN/plugins/ocpn_draw.html </info-url>
</plugin>
```

**Comment by jongough** [comment]
Raised on wrong repository, sorry. Move to [https://github.com/OpenCPN/OpenCPN/pull/1457](https://github.com/OpenCPN/OpenCPN/pull/1457)
